### ISSUE TITLE
WIRING  pinout needs additional  wire connection.

### ISSUE THREAD

**Issue by dkperf** [octal-ip/ESP8266_EPEVER_Tracer_Monitor#3]
Hi.  Project documentation is missing one wire connection under heading "WIRING".  
Project needs a connection (wire) from:

Logic level shifter	LV ( low voltage ) pin   TO    Wemos D1 Mini  3v3  pin.

Without 3.3v on LV  the Logic level shifter will NOT generate valid  LVx  when going from 5v to 3.3v.

**Comment by octal-ip** [comment]
Well spotted, thanks. I've updated the documentation.
